### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by RequestFX** [jbargu/mbr_virus#1]
I compiled virus.asm with nasm -o virus.bin virus.asm. But when booting, nothing happens...

**Comment by jbargu** [comment]
The virus was tested with FreeDOS, so I am not sure about its compatibility with later OS. For starters you need a MBR disk sector (in case you have GPT). Then you have to load the virus on a medium (e.g. USB) and boot from it in BIOS. This will trigger the logic to copy the virus to all existing disks. From there you could run a `dir` command in the command shell to see the virus working.

However this could be really far-fetched as far as I am concerned and I am probably missing/forgetting a lot of stuff on why it won't work (different syscalls, realmode, correct arch compilation ...). I can't really help you there since I haven't used Windows in 10+ years and I do not know the specifics. Indeed porting it could be a great exercise, if it is even possible.

Of course I do not take any responsibility if you mess something up, use a VM to play around.
